server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/labtest
    username: root
    password: hawkins123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true